inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-rails
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'config.ru'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'config/**'
    - 'config/initializers/devise.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'Gemfile'
    - 'health_cards.gemspec'

Style/Documentation:
  Exclude:
    - app/**/*
    - config/*
    - db/migrate/*
    - test/**/*
    - 'lib/health_cards/payload_types/covid_immunization_payload.rb'
    - 'lib/health_cards/payload_types/covid_lab_result_payload.rb'
    - 'lib/health_cards/payload_types/monkeypox_immunization_payload.rb'

Layout/BlockAlignment:
  EnforcedStyleAlignWith: 'start_of_block'

Layout/LineLength:
  Max: 121

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 25

Style/CollectionMethods:
  Enabled: true

Style/DoubleNegation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Rails/AssertNot:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: 'arguments'
