---
name: Docker Image CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

jobs:

  docker_build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: echo "skip / adapt to Kamal"
        # run: docker build -t health_cards .
