---
name: Ruby

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.0.6']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0.6']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install js dependencies
        run: yarn install
      - name: Run webpack
        run: bin/rake webpacker:install:react
      - name: Run tests
        run: bundle exec rake

  lint:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0.6']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rubocop
